dist: trusty
language: python
python:
    - '3.6'
install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"

    - conda config --set always_yes yes --set changeps1 no
    - conda create -n travis python=$TRAVIS_PYTHON_VERSION
    - conda env update -n travis -f conda/environment.yml
    - if [ -f conda/dev-environment-py${TRAVIS_PYTHON_VERSION}.yml ]; then conda env update -n travis -f conda/dev-environment-py${TRAVIS_PYTHON_VERSION}.yml; fi
    - source activate travis

    - pip install pytest
env:
  global:
    - PYTHONPATH=$PYTHONPATH:..:.
script:
    - py.test test
