name: ncigrafana

channels:
    - conda-forge
    - defaults

dependencies:
    - anaconda-client
    - conda-build
    - python
    - sqlite
    - pandas
    - matplotlib
    - numpy
    - dataset
    - sqlalchemy
    - Psycopg2

