name: ncigrafana

channels:
    - coecms
    - conda-forge
    - defaults

dependencies:
    - python
    - sqlite
    - dataset
    - pandas
    - matplotlib
    - numpy
    - dataset
    - sqlalchemy<2.0
    - Psycopg2

