package:
    name: ncimonitor
    version: {{ GIT_DESCRIBE_TAG}}

build:
    noarch: python
    number: {{ GIT_DESCRIBE_NUMBER }}
    script: python -m pip install --no-deps --ignore-installed .

source:
    git_url: ../

requirements:
    build:
        - python
        - pbr
    run:
        - python >3.5
        - numpy
        - pandas
        - dataset

test:
    imports:
        - ncimonitor
    requires:
        - pytest
    source_files:
        - conftest.py
        - test/**
    commands:
        - py.test

about:
    home: https://github.com/coecms/ncimonitor
