name: CD

on:
  push:
    branches:
        - master

env:
  PY_VERSION: 3.12

jobs:

  conda:
    name: Build with conda and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
            fetch-tags: true
            fetch-depth: 0

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@d2e6a045a86077fb6cad6f5adf368e9076ddaa8d # v3.1.0
        with:
          miniconda-version: "latest"
          python-version: ${{ env.PY_VERSION }}
          environment-file: conda/environment.yml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Build and upload the conda package
        uses: ACCESS-NRI/action-build-and-upload-conda-packages@3ba32e822e374fb238fa9b1c67107fd2791c2ae2 #v2.0.0
        with:
          meta_yaml_dir: conda
          user: accessnri
          label: main
          token: ${{ secrets.anaconda_token }}
